### ISSUE TITLE
Update to 1.3.2 breaks blind control

### ISSUE THREAD

**Issue by MichaelPlank** [ActiveByte/homebridge-loxone-connect#19]
Hi,
The update to 1.3.2 (changelog says 1.4.0) breaks the control of all my window blinds (Raffstores). Neither opening/closing nor setting the position works anymore.
I guess it has to do with the recently merged PR.

My Loxone Miniserver is on the latest update.

Going back to 1.3.1 where everything works smoothly.

**Comment by ActiveByte** [comment]
It indeed looks like a bug from the PR

**Comment by gschiidli** [comment]
I just had a look and could not find any obvious issue. I believe that it is some issue with the command that is sent, as that is the one major difference between the new shutters item and the blinds item. The fact that it does not move at all also points at a communications issue.

The command for the miniserver I got from [this document](https://www.loxone.com/dede/wp-content/uploads/sites/2/2021/11/1202_Structure-File.pdf). Which is version 12.2 which I guess matches the Loxone Config/firmware release.

Also tested it again with my Loxone setup and the blinds and shutters are working still fine for me 😕 I am running the miniserver on 12.4.2.28 (running the beta version because of some DALI issues of the current version) and have for example this configuration for my kitchen.

<img width="608" alt="Screenshot 2022-03-14 at 20 50 34" src="https://user-images.githubusercontent.com/36708010/158250611-a5e52c8e-5fcf-47fc-a149-73d3c04cc6c5.png">
<img width="184" alt="Screenshot 2022-03-14 at 20 51 01" src="https://user-images.githubusercontent.com/36708010/158250605-2332b190-3722-4b4e-8d65-a9009bd0cf45.png">

**Comment by MichaelPlank** [comment]
Hi @gschiidli, thx for looking into this issue.

I'm not using the "Automatic Blinds" module but the "Jalousien" (Blinds) module, which is a different one. 
Might that be the problem? Have you tested it with that module as well?

<img width="471" alt="Screenshot 2022-03-15 at 10 25 52" src="https://user-images.githubusercontent.com/231029/158348931-7c3377f3-2782-4b02-8037-097a1d701347.png">
<img width="329" alt="Screenshot 2022-03-15 at 10 26 14" src="https://user-images.githubusercontent.com/231029/158348943-b5c53904-dcd2-480a-8826-c0b383685d3b.png">

**Comment by gschiidli** [comment]
Thank you for the information @MichaelPlank. It would make sense that this could be the issue.

I switched my Loxone Config to German to match yours (I also speak German so no worries 😉) but sadly I can not find the block you use to try it out myself 😕 This are the available blocks for me:

<img width="675" alt="Screenshot 2022-03-15 at 18 26 05" src="https://user-images.githubusercontent.com/36708010/158436019-768580af-71cb-4fec-801a-153bb04247d2.png">

Can you still add the `Jalousie` block via the menu?
 
I also did some more investigation and the command I used to set the position with the slate angle at the same time is quite new. As far as I can see it was not supported on [version 12.0](https://www.loxone.com/dede/wp-content/uploads/sites/2/2021/03/1200_Structure-File.pdf). The change log for 12.1 say they fixed the command for `Integrated Auto jalousie`. How they fix a command that was previously not available is something I don't understand though.

<img width="626" alt="image" src="https://user-images.githubusercontent.com/36708010/158440635-5cfb201a-3b75-4e9b-8361-37f60b5a263d.png">

Can you share your firmware and Loxone Config version?

**Comment by MichaelPlank** [comment]
Hi @gschiidli,
that's really interesting, I also don't find the "Jalousie" module in the menu anymore. It might have become deprecated.
I have my config already for around 6 years.

I have tried to use the "Automated Blinds" (Automatikjalousie) module for one of my blinds and tested it with 1.3.2. This works. So it seems the problem is related with the "old?" "Jalousie" module.

Here's my Loxone config version and Miniserver version.
<img width="286" alt="Screenshot 2022-03-15 at 19 48 11" src="https://user-images.githubusercontent.com/231029/158457282-28f54af4-d10e-4d02-a3d4-a22211311f34.png">
<img width="788" alt="Screenshot 2022-03-15 at 19 50 56" src="https://user-images.githubusercontent.com/231029/158457289-7da0e3c2-2ced-48ee-8ea2-c5824e6e43b6.png">

**Comment by MichaelPlank** [comment]
Fine for me.
